[package]
name = "raui-tesselate-renderer"
version = "0.36.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"
description = "RAUI renderer that tesselates layout into vertex and index buffers"
readme = "../README.md"
license = "MIT"
repository = "https://github.com/RAUI-labs/raui"
keywords = ["renderer", "agnostic", "ui", "interface", "gamedev"]
categories = ["gui", "rendering::graphics-api"]

[features]
scalar64 = ["raui-core/scalar64"]
integer64 = ["raui-core/integer64"]
index32 = []

[dependencies]
raui-core = { path = "../raui-core", version = "0.36" }
serde = { version = "1", features = ["derive"] }
vek = "0.15"
